name: Docker Security Scan

on:
  workflow_dispatch:  # Allows manual triggers
  pull_request:
    branches: [ master ]

jobs:
  scan-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build frontend image
        run: docker build -t tic-tac-toe-frontend:${{ github.sha }} ./frontend

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: tic-tac-toe-frontend:${{ github.sha }}
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

  scan-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build backend image
        run: docker build -t tic-tac-toe-backend:${{ github.sha }} ./backend

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: tic-tac-toe-backend:${{ github.sha }}
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
